<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Observatory.Communicator</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <VersionSuffix>0.0.2.$([System.DateTime]::UtcNow.DayOfYear.ToString().PadLeft(3, "0"))$([System.DateTime]::UtcNow.Hour)</VersionSuffix>
    <AssemblyVersion Condition=" '$(VersionSuffix)' == '' ">0.0.0.1</AssemblyVersion>
    <AssemblyVersion Condition=" '$(VersionSuffix)' != '' ">$(VersionSuffix)</AssemblyVersion>
    <Version Condition=" '$(VersionSuffix)' == '' ">0.0.1.0</Version>
    <Version Condition=" '$(VersionSuffix)' != '' ">$(VersionSuffix)</Version>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec
      Condition=" '$(OS)' == 'Windows_NT' "
      Command="xcopy &quot;$(TargetDir)*&quot; &quot;$(ProjectDir)..\ObservatoryCore\$(OutDir)..\net8.0-windows7.0\plugins\ObservatoryCommunicator\&quot; /y /s /exclude:$(ProjectDir)..\xcopyExclude"
    />
  </Target>

  <ItemGroup>
    <ProjectReference Include="..\ObservatoryFramework\ObservatoryFramework.csproj" />
  </ItemGroup>
</Project>
